apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: data-entry
  name: data-entry
spec:
    type: LoadBalancer
    loadBalancerIP: 34.71.104.214
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: data-entry
status:
  loadBalancer: {}

